/*
Nrandaf_EventExposure

RANDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package randaf

import (
	"encoding/json"
	"fmt"
)

// RandafEventType Describes the supported event types of Nrandaf_EventExposure Service
type RandafEventType struct {
	RandafEventTypeAnyOf *RandafEventTypeAnyOf
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RandafEventType) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into RandafEventTypeAnyOf
	err = json.Unmarshal(data, &dst.RandafEventTypeAnyOf);
	if err == nil {
		jsonRandafEventTypeAnyOf, _ := json.Marshal(dst.RandafEventTypeAnyOf)
		if string(jsonRandafEventTypeAnyOf) == "{}" { // empty struct
			dst.RandafEventTypeAnyOf = nil
		} else {
			return nil // data stored in dst.RandafEventTypeAnyOf, return on the first match
		}
	} else {
		dst.RandafEventTypeAnyOf = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(RandafEventType)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *RandafEventType) MarshalJSON() ([]byte, error) {
	if src.RandafEventTypeAnyOf != nil {
		return json.Marshal(&src.RandafEventTypeAnyOf)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableRandafEventType struct {
	value *RandafEventType
	isSet bool
}

func (v NullableRandafEventType) Get() *RandafEventType {
	return v.value
}

func (v *NullableRandafEventType) Set(val *RandafEventType) {
	v.value = val
	v.isSet = true
}

func (v NullableRandafEventType) IsSet() bool {
	return v.isSet
}

func (v *NullableRandafEventType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRandafEventType(val *RandafEventType) *NullableRandafEventType {
	return &NullableRandafEventType{value: val, isSet: true}
}

func (v NullableRandafEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRandafEventType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


